version: "3.8"
services:
  spring-boot-gradled1a2cc4a-52bf-466f-96ce-5ca32b61fb5c:
    container_name: d1a2cc4a-52bf-466f-96ce-5ca32b61fb5c
    build:
      context: ./backend
    ports:
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://hyeseoni:aaa@mongodb:27018/testdb
      MONGO_INITDB_ROOT_USERNAME: hyeseoni
      MONGO_INITDB_ROOT_PASSWORD: aaa
      CORS_ALLOWED_ORIGIN: http://13.124.154.154:0
    networks:
      - dobie
  mongodb:
    container_name: 21d37912-1a02-4063-8c7b-9894de680314
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: hyeseoni
      MONGO_INITDB_ROOT_PASSWORD: aaa
    ports:
      - "27018:27017"
    volumes:
      - mongodb-data:/var/lib/mongodb
    networks:
      - dobie
volumes:
  mongodb-data:
networks: 
  dobie: 
    external: true 